#!/bin/bash
#SBATCH -N 1
#SBATCH -C haswell
#SBATCH -q debug
#SBATCH -J jobCoriDemoGerbil
#SBATCH -o jobCoriDemoGerbil.%j.stdout
#SBATCH -e jobCoriDemoGerbil.%j.error
#SBATCH --mail-user=gguidi@berkeley.edu
#SBATCH --mail-type=ALL
#SBATCH -t 30:00
#SBATCH -c 64

#OpenMP settings:
export OMP_NUM_THREADS=64
export OMP_PLACES=threads
export OMP_PROC_BIND=false

cd /global/cscratch1/sd/gguidi/bella/
module unload gcc/7.3.0
module load gcc/6.1.0
module swap PrgEnv-intel PrgEnv-gnu
module load boost

#compile the application
make clean
make bellai

#work directory
mkdir jobCoriDemoGerbil$jobid
cd jobCoriDemoGerbil$jobid

#run the application CPU only
srun -n 1 -c 64 /global/cscratch1/sd/gguidi/bella/./bella -i /global/cscratch1/sd/gguidi/bella/input-ecsample.txt -d 30 -o jobCoriDemoGerbil$jobid -g 
